Feat/39 implement a frontend page to display products
stephane-segning/compustore pull request #23
Opened 2024-12-05 08:19 UTC by kouamschekina

2024-12-06 09:23 UTC, stephane-segning requested changes

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
Nice work! But bulky. Please, split this into smaller components.

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +'use client';
You want to avoid using `use client` in `page.tsx` components as much as possible. If a logic requires that, put that but into a sub-component

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +      </nav>
This is a menu. You typically want to use it in a `layout.tsx` component.

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +  </div>
This section could be done using product's images.

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +</footer>
This can be done in a another component, and imported again in a `layout.tsx` again

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +  </div>
This can also be done using another component and imported here

2024-12-06 09:23 UTC, stephane-segning commented on src/app/(main)/product/page.tsx
> +      </nav>
This can be done in a another component, and imported again in a `layout.tsx` again

2025-01-08 08:42 UTC, stephane-segning approved these changes
Nice!

2025-01-08 08:45 UTC, bryandino673 approved these changes

2025-01-08 14:18 UTC, Ngha-Boris commented on next.config.js
> +      },
Have you figured out how to do this another way?
If so, please let me know. I just don't like the fact that we are passing the domain for every image in this file.

2025-01-08 14:25 UTC, kouamschekina commented on next.config.js
> +      },
Not yet
I am still working on that

2025-01-08 15:50 UTC, Ngha-Boris approved these changes
Nice

2025-01-08 15:50 UTC, Ngha-Boris commented on next.config.js
> +      },
Me too

2025-01-09 07:04 UTC, merged