Feat/45 implement a product details page in next.js displaying specs images and description
stephane-segning/compustore pull request #24
Opened 2024-12-05 13:03 UTC by Ngha-Boris

2024-12-06 09:55 UTC, stephane-segning requested changes

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +"use client";
You want to avoid using `use client` in `page.tsx` components as much as possible. If a logic requires that, put that but into a sub-component

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +}
Nice one 👍🏿

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +  }));
This part would be impossible without `use client`. So better abstract it into a sub-component, or even multiple.

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +      </Head>
Instead of this, using https://nextjs.org/docs/app/api-reference/functions/generate-metadata is a better option.

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
Add but the `use client` here. This component uses `useState`

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
> +            />
In NextJS, always use Image, their very own component.

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
> +            />
Same

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
> +          </button>
Why not use our custom button component?

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
> +              </div>
Why is this not a button?

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +          <p className="text-gray-200 mb-4">{description}</p>
Remove gray from the classes. Use our colors

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +      <nav className="bg-gray-400 text-white p-4 flex justify-between">
Don't use other colors, rather than gray

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
> +            }`}
For such behaviours, use tailwind-merge. It's already installed

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +          </Button>
Why not use the props of the custom button? Why use again another class here? Remove it and use the provided color.

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +          <Button className="w-8 h-8 rounded-full bg-neutral-light flex justify-center items-center">A</Button>
What's the interest of having a component, while not using it properly? Remove those class and use the object's.

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +      </div>
Create a component for this

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +      </div>
Create a component for this

2024-12-06 09:55 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +          </a>
This looks like a title in the navbar. Please remove it. In the #23, should already be implemented something for that.

2024-12-06 09:55 UTC, stephane-segning commented on src/components/image/image.tsx
> +  return <img src={src} alt={alt} className="w-64 h-auto object-contain" />;
Use Image from the nextjs's library

2025-01-08 08:49 UTC, stephane-segning requested changes
Please address these points

2025-01-08 08:49 UTC, stephane-segning commented on src/app/(main)/product/[id]/page.tsx
> +        <title>Product Details</title>
Why not use the title of the product as title of the page?

2025-01-08 08:49 UTC, stephane-segning commented on src/components/image/image-gallery.tsx
Please add some storybooks for this and all your dumb components too

2025-01-08 08:49 UTC, stephane-segning commented on src/components/product/product-details.tsx
> +'use client'
Why do you need `use client` here?

2025-01-08 08:49 UTC, stephane-segning commented on src/components/image/image.tsx
> +  return <img src={src} alt={alt} className="w-64 h-auto object-contain" />;
Use the `Image` component from next js as base tag here

2025-01-08 14:38 UTC, kouamschekina approved these changes
Nice

2025-01-08 15:27 UTC, mbunwe-victor approved these changes
Good

2025-01-08 15:59 UTC, kouamschekina approved these changes

2025-01-09 00:09 UTC, stephane-segning approved these changes

2025-01-09 06:58 UTC, merged