feat: added a filter component to filter products by category
stephane-segning/compustore pull request #27
Opened 2024-12-06 09:56 UTC by Valsuh45

2024-12-06 10:08 UTC, stephane-segning requested changes

2024-12-06 10:08 UTC, stephane-segning commented on src/components/filter/filter-dropdown.tsx
> +      </button>
Why not use our custom button component?

2024-12-06 10:08 UTC, stephane-segning commented on src/components/filter/filter.tsx
> +        </button>
Why not use our custom button component?

2024-12-06 10:08 UTC, stephane-segning commented on src/styles/globals.scss
> +  background: var(--primary-color);
Use tailwind instead

2024-12-06 10:08 UTC, stephane-segning commented on src/components/filter/index.ts
Don't do this. Import default first. Then export it as default again

2025-01-08 08:38 UTC, Valsuh45 commented on src/components/filter/filter-dropdown.tsx
> +      </button>
Well noted, will work on it

2025-01-08 08:39 UTC, Valsuh45 commented on src/styles/globals.scss
> +  background: var(--primary-color);
Ok @stephane-segning 
Will implement it in Tailwind then

2025-01-08 11:28 UTC, Valsuh45 commented on src/components/filter/index.ts
Ok Sir, will adjust it as required

2025-01-08 11:54 UTC, Valsuh45 commented
Hi @stephane-segning  and @bryandino673 
I'm done with the requested changes :+1: 
Kindly review and give your feedback.

2025-01-08 13:34 UTC, Valsuh45 commented on src/components/filter/filter.scss
> +@tailwind utilities;
Oh, that's an oversight on my part Sir. These tailwind directives are unnecessary here because Tailwind CSS is already imported and applied globally in global.scss

2025-01-08 14:42 UTC, bryandino673 approved these changes

2025-01-08 14:49 UTC, merged