Feat/44 create a detailed product api endpoint for fetching individual product details
stephane-segning/compustore pull request #8
Opened 2024-11-26 10:32 UTC by Ngha-Boris

2024-11-26 10:40 UTC, stephane-segning requested changes

2024-11-26 10:40 UTC, stephane-segning commented on .hintrc
> +}
Remove this please

2024-11-26 10:40 UTC, stephane-segning commented on package.json
> +    "@testing-library/react-hooks": "^8.0.1",
Why?

2024-11-26 10:40 UTC, stephane-segning commented on package.json
> +    "@trpc/react-query": "^10.45.2",
Why changing the version?

2024-11-26 10:57 UTC, stephane-segning commented on package.json
> +    "msw": "^2.6.4",
Remove this please

2024-11-26 11:19 UTC, stephane-segning requested changes

2024-11-26 11:19 UTC, stephane-segning commented on yarn.lock
Why did this file changed?

2024-11-26 12:46 UTC, Ngha-Boris commented on yarn.lock
Sir @stephane-segning I am also sure is because I removed some libraries in the package.json, like for example the msw library

2024-11-26 17:26 UTC, stephane-segning approved these changes

2024-11-27 06:40 UTC, mbunwe-victor reviewed
Good @Ngha-Boris

2024-11-27 06:41 UTC, mbunwe-victor approved these changes
Good @Ngha-Boris

2024-11-27 06:42 UTC, bryandino673 approved these changes

2024-11-27 06:42 UTC, merged